"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

import type { InvoiceEntity } from "@/core/domain/entities/invoice-entity";
import { calculateInvoiceTotals } from "@/core/use-cases/calculate-vat";
import { normalizeNip } from "@/core/use-cases/validate-nip";
import { SupabaseInvoiceRepository } from "@/infrastructure/supabase/queries/invoice-repository";
import { createSupabaseServerClient } from "@/infrastructure/supabase/server-client";
import { invoiceFormSchema, type InvoiceFormValues } from "@/lib/schemas/invoice";
import { KSeFApiClient } from "@/infrastructure/ksef/ksef-api-client";
import { KSeFService } from "@/infrastructure/ksef/ksef-service";
import type { KsefEnvironment } from "@/infrastructure/ksef/ksef-types";

const repository = new SupabaseInvoiceRepository();
const ksefService = new KSeFService();

export async function createInvoiceAction(values: InvoiceFormValues) {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return { error: "Brak autoryzacji." };
  }

  const parsed = invoiceFormSchema.safeParse(values);
  if (!parsed.success) {
    return { error: "Nieprawidłowe dane faktury." };
  }

  const totals = calculateInvoiceTotals(values.items);

  const invoice: InvoiceEntity = {
    id: "", // Will be generated by DB
    userId: user.id,
    number: values.number,
    type: values.type,
    issueDate: values.issueDate,
    saleDate: values.saleDate,
    dueDate: values.dueDate,
    status: values.status,
    issuer: {
      name: values.issuerName,
      nip: normalizeNip(values.issuerNip),
      address: values.issuerAddress,
    },
    client: {
      name: values.clientName,
      nip: normalizeNip(values.clientNip),
      address: values.clientAddress,
    },
    items: values.items,
    totalNet: totals.net,
    totalVat: totals.vat,
    totalGross: totals.gross,
    isDraft: false, // Default for now
    ksefStatus: "none",
  };

  try {
    const id = await repository.create(invoice);
    revalidatePath("/dashboard");
    revalidatePath("/invoices");
    return { id };
  } catch (error) {
    console.error("Error creating invoice:", error);
    return { error: "Nie udało się zapisać faktury." };
  }
}

export async function updateInvoiceAction(id: string, values: InvoiceFormValues) {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return { error: "Brak autoryzacji." };
  }

  // Verify ownership and KSeF status before update
  const existing = await repository.getByIdForUser(id, user.id);
  if (!existing) {
    return { error: "Faktura nie znaleziona." };
  }

  if (existing.ksefStatus && existing.ksefStatus !== "none" && existing.ksefStatus !== "rejected") {
    return { error: "Nie można edytować faktury wysłanej do KSeF." };
  }

  const parsed = invoiceFormSchema.safeParse(values);
  if (!parsed.success) {
    return { error: "Nieprawidłowe dane faktury." };
  }

  const totals = calculateInvoiceTotals(values.items);

  const updatedEntity: InvoiceEntity = {
    ...existing,
    number: values.number,
    type: values.type,
    issueDate: values.issueDate,
    saleDate: values.saleDate,
    dueDate: values.dueDate,
    status: values.status,
    issuer: {
      name: values.issuerName,
      nip: normalizeNip(values.issuerNip),
      address: values.issuerAddress,
    },
    client: {
      name: values.clientName,
      nip: normalizeNip(values.clientNip),
      address: values.clientAddress,
    },
    items: values.items,
    totalNet: totals.net,
    totalVat: totals.vat,
    totalGross: totals.gross,
  };

  try {
    await repository.update(id, updatedEntity);
    revalidatePath("/dashboard");
    revalidatePath("/invoices");
    revalidatePath(`/invoices/${id}`);
    return { success: true };
  } catch (error) {
    console.error("Error updating invoice:", error);
    return { error: "Nie udało się zaktualizować faktury." };
  }
}

export async function sendToKSeFAction(id: string) {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return { error: "Brak autoryzacji." };
  }

  const invoice = await repository.getByIdForUser(id, user.id);
  if (!invoice) {
    return { error: "Faktura nie znaleziona." };
  }

  if (invoice.ksefStatus === "accepted" || invoice.ksefStatus === "pending") {
    return { error: "Faktura jest już w systemie KSeF lub w trakcie przetwarzania." };
  }

  // KSeF Config from environment
  const ksefToken = process.env.KSEF_API_TOKEN;
  const ksefNip = process.env.KSEF_NIP || invoice.issuer.nip;
  const ksefEnv = (process.env.KSEF_ENV || "DEMO") as KsefEnvironment;

  if (!ksefToken) {
    return { error: "Brak skonfigurowanego tokena KSeF (KSEF_API_TOKEN)." };
  }

  try {
    const client = new KSeFApiClient(ksefEnv, ksefNip, ksefToken);

    // 1. Generate XML FA(3)
    const xml = ksefService.generateFA3Xml(invoice);

    // 2. Auth Flow v2 (Challenge + Encrypted Login + Session Init)
    const sessionToken = await client.loginAndGetToken();

    // 3. Send Invoice to active session
    const sendRes = await client.sendInvoiceInSession(xml, sessionToken);

    // 4. Close Session
    await client.closeSession(sessionToken);

    // 5. Update Local Database
    await repository.update(id, {
      ...invoice,
      ksefStatus: "pending",
      ksefId: sendRes.elementReferenceNumber, // Reference number for tracking
    });

    revalidatePath(`/invoices/${id}`);
    return { 
      success: true, 
      message: "Faktura została pomyślnie wysłana do systemu KSeF (v2).",
      ksefId: sendRes.elementReferenceNumber 
    };
  } catch (error) {
    console.error("KSeF v2 Error:", error);
    return { 
      error: error instanceof Error ? error.message : "Wystąpił błąd podczas wysyłki do KSeF (v2)." 
    };
  }
}

export async function deleteInvoiceAction(id: string) {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return { error: "Brak autoryzacji." };
  }

  // Verify ownership and KSeF status before delete
  const existing = await repository.getByIdForUser(id, user.id);
  if (!existing) {
    return { error: "Faktura nie znaleziona." };
  }

  if (existing.ksefStatus && existing.ksefStatus !== "none" && existing.ksefStatus !== "rejected") {
    return { error: "Nie można usunąć faktury wysłanej do KSeF." };
  }

  try {
    await repository.delete(id);
    revalidatePath("/dashboard");
    revalidatePath("/invoices");
    return { success: true };
  } catch (error) {
    console.error("Error deleting invoice:", error);
    return { error: "Nie udało się usunąć faktury." };
  }
}
